name: JSON Artifact

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    name: JSON Artifact
    runs-on: ubuntu-latest
    steps:
      - name: JSON file
        run: |
          echo '{"key-example": "value-example"}' > artifact-example.json

      - name: Install JC
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: jc
          version: 1.0

      - name: Test JC
        run: jc -h

      - name: Upload JSON Artifact
        uses: actions/upload-artifact@v4
        with:
          name: json-artifact-example
          path: artifact-example.json
