name: Lint

on:
  workflow_run:
    workflows: [Artifact]
    types: [completed]

permissions:
  contents: write
  statuses: write
  id-token: write
  actions: read
  pull-requests: write

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-Linter
        uses: super-linter/super-linter@v7.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIX_SHELL_SHFMT: true
          FIX_YAML_PRETTIER: true
          VALIDATE_CHECKOV: false
