name: Lint

on:
  workflow_run:
    workflows: [JSON Artifact]
    branches: [dev]
    types: [requested]

#on:
#  push: null
#  pull_request: null

permissions:
  contents: write
  statuses: write

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Super-Linter
        uses: super-linter/super-linter@v7.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIX_SHELL_SHFMT: true
          FIX_YAML_PRETTIER: true
          VALIDATE_CHECKOV: false
